version: '3'
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile1
    ports:
      - "8090:8080"
  mongodb:  
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - C:\MongoDB:/data/db